//! Gate A: the property-test gate (round-2 §7 tests 1, 3, 5) for the
//! transaction channel (Tasks 1-7). Lives as an integration test because the
//! whole surface it exercises (`Session`, `Tx`, `control::op::*`) is already
//! `pub` through `aura_lib::control` — no visibility changes were needed to
//! reach it from here, which is why this suite sits in `tests/` rather than
//! as a `#[cfg(test)]` module inside `src/control/session.rs` (that would
//! have required nothing extra either, but this keeps property-test-only
//! dependencies, like `proptest`, out of the crate's own `#[cfg(test)]`
//! compilation unit and mirrors how the crate already separates unit tests
//! (in-module) from integration coverage (this directory)).
//!
//! Test helpers here (`fresh_session_3_tracks`, `test_track`, `user_meta`,
//! `set_gain`) are deliberately NOT the private ones in
//! `src/control/session.rs`'s `#[cfg(test)]` module (those are crate-private
//! and unreachable from an integration test) — this file defines its own,
//! parallel but independent.
//!
//! Gate B (Task 8) lifts Task 1's original clip-free exclusion:
//! `arb_op_batches`'s `TrackAdd`/`TrackRemove` now attach 0..2 freshly-minted
//! clips, so `undo_round_trip`'s byte-stability oracle also covers
//! clip-carrying histories, not just bare track rows. (The dedicated
//! delete-then-undo identity property — random SUBSETS of tracks removed one
//! at a time, with interleaved clip ownership across the whole store — lives
//! in `tests/identity_properties.rs`; this file's coverage is the general
//! Gate A op-batch fuzzer, now clip-aware.)

use proptest::prelude::*;

use aura_lib::audio::types::{Clip, Store, TrackState};
use aura_lib::control::op::{Actor, ObjectRef, Op, PropPath, TxMeta};
use aura_lib::control::Session;
use aura_lib::ids::{ContentId, LaneId, SourceId};
use aura_lib::midi::MidiStore;

// ---------------------------------------------------------------------------
// Local test helpers (independent of session.rs's private #[cfg(test)] ones)
// ---------------------------------------------------------------------------

/// A session seeded with exactly 3 tracks, ids `t-1`..`t-3`, no clips. The
/// property strategy's model (`alive: Vec<String>`) starts from these same
/// three ids — keep them in sync if either side changes.
fn fresh_session_3_tracks() -> parking_lot::Mutex<Session> {
    let mut store = Store::default();
    for id in SEED_IDS {
        store.tracks.push(test_track(id));
    }
    parking_lot::Mutex::new(Session::new(store, MidiStore::default()))
}

const SEED_IDS: [&str; 3] = ["t-1", "t-2", "t-3"];

/// A standalone `TrackState` row with values inside every clamp range
/// (`session.rs::write_prop`), used both for the seeded session and for
/// `TrackAdd`/`TrackRemove` op payloads generated by the strategy.
fn test_track(id: &str) -> TrackState {
    TrackState {
        id: id.into(),
        name: format!("Track {id}"),
        kind: "audio".into(),
        gain_db: 0.0,
        pan: 0.0,
        muted: false,
        soloed: false,
        armed: false,
        color: "#7c9cff".into(),
        instrument_id: None,
    }
}

fn user_meta(label: &str) -> TxMeta {
    TxMeta { actor: Actor::User, run: "prop-run".into(), label: label.into(), transient: false }
}

/// A standalone `Clip` row for `TrackAdd`/`TrackRemove` op payloads (Gate B
/// clip-carrying coverage). The empty/default `SourceId` is the documented
/// "unassigned" sentinel (`audio/types.rs::Clip::source_id`) — fine here,
/// these clips never reach the engine's decode cache.
fn test_clip(id: &str, track_id: &str) -> Clip {
    Clip {
        id: id.into(),
        track_id: track_id.into(),
        name: format!("Clip {id}"),
        source_path: "audio/x.wav".into(),
        source_id: SourceId::default(),
        source_channels: 2,
        source_sample_rate: 48_000,
        source_length_samples: 48_000,
        timeline_start_samples: 0,
        offset_samples: 0,
        length_samples: 48_000,
        gain_db: 0.0,
        fade_in_samples: 0,
        fade_out_samples: 0,
        content_id: ContentId::mint(),
        lane_id: LaneId::default_for_track(track_id),
    }
}

/// `from` is intentionally `Null`: it's advisory only — `apply_raw` re-reads
/// truth from the store and ignores the caller's `from`.
fn set_gain(track_id: &str, to: f64) -> Op {
    Op::Set {
        object: ObjectRef::Track(track_id.into()),
        path: PropPath::Gain,
        from: serde_json::Value::Null,
        to: serde_json::json!(to),
    }
}

/// Deep, byte-identical snapshot of session STATE — `Store` + `MidiStore`'s
/// public fields, serialized to canonical JSON. Deliberately does NOT reach
/// `Session.rev` (it's `pub(crate)`, unreachable from this integration test
/// crate anyway) — `rev` increments on every transaction including undo
/// transactions, which is correct behavior, not something snapshot equality
/// should be sensitive to. Round-2 §2.4: `Store` no longer owns a `slots`
/// map (slots are per-graph-generation state derived fresh by the engine on
/// every rebuild, never part of the document) — so there is nothing RT-side
/// left to snapshot here; `tracks`/`clips` order IS the display order the
/// slots would be derived from, and that's already covered below.
fn snapshot(m: &parking_lot::Mutex<Session>) -> String {
    #[derive(serde::Serialize)]
    struct StoreSnap<'a> {
        transport: &'a aura_lib::audio::types::TransportState,
        tracks: &'a Vec<TrackState>,
        clips: &'a Vec<aura_lib::audio::types::Clip>,
        project_dir: &'a Option<std::path::PathBuf>,
        project_name: &'a Option<String>,
        created_at: &'a Option<String>,
    }
    #[derive(serde::Serialize)]
    struct MidiSnap<'a> {
        ppq: u32,
        tempo_events: &'a Vec<aura_lib::midi::TempoEvent>,
        clips: &'a Vec<aura_lib::midi::MidiClip>,
        loaded_dir: &'a Option<std::path::PathBuf>,
    }
    #[derive(serde::Serialize)]
    struct Snap<'a> {
        store: StoreSnap<'a>,
        midi: MidiSnap<'a>,
    }

    let g = m.lock();
    let snap = Snap {
        store: StoreSnap {
            transport: &g.store.transport,
            tracks: &g.store.tracks,
            clips: &g.store.clips,
            project_dir: &g.store.project_dir,
            project_name: &g.store.project_name,
            created_at: &g.store.created_at,
        },
        midi: MidiSnap {
            ppq: g.midi.ppq,
            tempo_events: &g.midi.tempo_events,
            clips: &g.midi.clips,
            loaded_dir: &g.midi.loaded_dir,
        },
    };
    serde_json::to_string(&snap).expect("snapshot fields are all plain-data Serialize")
}

// ---------------------------------------------------------------------------
// arb_op_batches: a Vec<Vec<Op>> strategy, model-threaded so every generated
// op targets a currently-alive track id (Sets and Removes) or introduces a
// genuinely fresh one (Adds) — batches are valid by construction. Threading
// happens in a deterministic `prop_map` over pure random primitives (usize
// picks + typed values), not by calling anything nondeterministic (e.g. no
// `Uuid::new_v4()` inside the map) — that keeps proptest's shrinker honest:
// shrinking the underlying raw ints/bools must still resolve to the same
// concrete ops on replay.
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
enum SetKind {
    Gain(f64),
    Pan(f64),
    Muted(bool),
    Soloed(bool),
    Armed(bool),
}

#[derive(Debug, Clone)]
enum RawAction {
    /// `pick` selects an alive track by `pick % alive.len()`.
    Set(usize, SetKind),
    /// `n_clips` (0..=2) freshly-minted clips travel with the new row
    /// (Gate B: Task 1's clip-free exclusion lifted).
    Add(usize),
    /// `pick` selects an alive track by `pick % alive.len()`; `n_clips`
    /// (0..=2) freshly-minted clips are attached to the op payload — advisory
    /// only (`apply_raw` collects the REAL removed clips from store truth),
    /// but exercised anyway so a clip-carrying `TrackRemove` payload is part
    /// of the fuzzed op vocabulary too.
    Remove(usize, usize),
}

fn set_kind_strategy() -> impl Strategy<Value = SetKind> {
    prop_oneof![
        (-160.0f64..=24.0f64).prop_map(SetKind::Gain),
        (-1.0f64..=1.0f64).prop_map(SetKind::Pan),
        any::<bool>().prop_map(SetKind::Muted),
        any::<bool>().prop_map(SetKind::Soloed),
        any::<bool>().prop_map(SetKind::Armed),
    ]
}

/// Weighted so removes land often enough (against a growing/shrinking model,
/// starting from 3 seeded tracks) to exercise restore-at-varied-index, while
/// Adds keep replenishing the pool so batches don't degenerate into
/// all-no-op Sets/Removes against an empty track list.
fn raw_action_strategy() -> impl Strategy<Value = RawAction> {
    prop_oneof![
        4 => (any::<usize>(), set_kind_strategy()).prop_map(|(p, k)| RawAction::Set(p, k)),
        2 => (0usize..=2).prop_map(RawAction::Add),
        3 => (any::<usize>(), 0usize..=2).prop_map(|(p, n)| RawAction::Remove(p, n)),
    ]
}

/// Mint `n` freshly-numbered clips owned by `track_id`, advancing
/// `clip_counter` (kept separate from the track-id `counter` so ids never
/// collide across the two families).
fn mint_clips(track_id: &str, n: usize, clip_counter: &mut u32) -> Vec<Clip> {
    (0..n)
        .map(|_| {
            let cid = format!("clip-{}", *clip_counter);
            *clip_counter += 1;
            test_clip(&cid, track_id)
        })
        .collect()
}

/// Resolves one `RawAction` against the threaded model, mutating `alive`,
/// `counter` (fresh, distinct generated-track ids) and `clip_counter` (fresh,
/// distinct generated-clip ids). Returns `None` when the action is a no-op
/// given current model state (e.g. a Set/Remove drawn while `alive` is
/// empty) — the caller filters those out, so a batch may end up shorter than
/// requested (never invalid).
fn resolve_one(
    action: RawAction, alive: &mut Vec<String>, counter: &mut u32, clip_counter: &mut u32,
) -> Option<Op> {
    match action {
        RawAction::Set(pick, kind) => {
            if alive.is_empty() {
                return None;
            }
            let id = alive[pick % alive.len()].clone();
            let (path, to) = match kind {
                SetKind::Gain(v) => (PropPath::Gain, serde_json::json!(v)),
                SetKind::Pan(v) => (PropPath::Pan, serde_json::json!(v)),
                SetKind::Muted(v) => (PropPath::Muted, serde_json::json!(v)),
                SetKind::Soloed(v) => (PropPath::Soloed, serde_json::json!(v)),
                SetKind::Armed(v) => (PropPath::Armed, serde_json::json!(v)),
            };
            Some(Op::Set { object: ObjectRef::Track(id.into()), path, from: serde_json::Value::Null, to })
        }
        RawAction::Add(n_clips) => {
            let id = format!("gen-{}", *counter);
            *counter += 1;
            alive.push(id.clone());
            // `clip_indices` stays empty: `apply_raw`'s TrackAdd arm falls
            // back to appending (`clip_indices.len() == clips.len()` is
            // false for empty indices against non-empty clips), which is
            // exactly right for a genuinely NEW row — there is no prior
            // position to restore.
            let clips = mint_clips(&id, n_clips, clip_counter);
            Some(Op::TrackAdd {
                track: test_track(&id), index: alive.len() - 1, clips, clip_indices: vec![],
            })
        }
        RawAction::Remove(pick, n_clips) => {
            if alive.is_empty() {
                return None;
            }
            let idx = pick % alive.len();
            let id = alive.remove(idx);
            // `track`/`clips`/`clip_indices` are all advisory-ignored by
            // `apply_raw` (store truth wins for the removed row and its
            // real clips) — only `.id` matters for finding the row to
            // remove. Attaching minted clips here anyway exercises that
            // "advisory, ignored" path even when the payload itself carries
            // clips.
            let clips = mint_clips(&id, n_clips, clip_counter);
            Some(Op::TrackRemove { track: test_track(&id), index: idx, clips, clip_indices: vec![] })
        }
    }
}

fn arb_op_batches(num_batches: std::ops::Range<usize>) -> impl Strategy<Value = Vec<Vec<Op>>> {
    proptest::collection::vec(proptest::collection::vec(raw_action_strategy(), 1..=4), num_batches)
        .prop_map(|raw_batches| {
            let mut alive: Vec<String> = SEED_IDS.iter().map(|s| s.to_string()).collect();
            let mut counter: u32 = 0;
            let mut clip_counter: u32 = 0;
            raw_batches
                .into_iter()
                .map(|batch| {
                    batch
                        .into_iter()
                        .filter_map(|a| resolve_one(a, &mut alive, &mut counter, &mut clip_counter))
                        .collect::<Vec<Op>>()
                })
                .collect()
        })
}

// ---------------------------------------------------------------------------
// Gate tests
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// Gate test 1: apply all, undo all, byte-identical state.
    #[test]
    fn undo_round_trip(batches in arb_op_batches(1..20)) {
        let m = fresh_session_3_tracks();
        let before = snapshot(&m);
        let mut undo_stack = vec![];
        for b in batches {
            if let Ok(c) = Session::transact(&m, user_meta("p"), |tx| {
                for op in b {
                    tx.apply(op)?;
                }
                Ok(())
            }) {
                undo_stack.push(c.inverses);
            } // Err = rolled back = state unchanged; nothing pushed.
        }
        for inv in undo_stack.into_iter().rev() {
            Session::transact(&m, user_meta("undo"), |tx| {
                for op in inv {
                    tx.apply(op)?;
                }
                Ok(())
            })
            .unwrap();
        }
        prop_assert_eq!(snapshot(&m), before);
    }

    /// Gate test 3: a failing batch leaves the session exactly as it was.
    #[test]
    fn atomicity(prefix in arb_op_batches(1..5)) {
        let m = fresh_session_3_tracks();
        let before = snapshot(&m);
        let _ = Session::transact(&m, user_meta("f"), |tx| {
            for b in prefix {
                for op in b {
                    tx.apply(op)?;
                }
            }
            tx.apply(set_gain("no-such-track", 0.5)) // guaranteed failure
        });
        prop_assert_eq!(snapshot(&m), before);
    }
}

/// Gate test 5: every committed batch carries resolvable attribution.
#[test]
fn attribution_survives_commit() {
    let m = fresh_session_3_tracks();
    let c = Session::transact(
        &m,
        TxMeta { actor: Actor::Agent { tool: "set_track_mix".into() }, run: "run-42".into(), label: "agent mix".into(), transient: false },
        |tx| tx.apply(set_gain("t-1", 0.5)),
    )
    .unwrap();
    assert!(matches!(c.meta.actor, Actor::Agent { ref tool } if tool == "set_track_mix"));
    assert_eq!(c.meta.run, "run-42");
}
