//! Gate A: the property-test gate (round-2 §7 tests 1, 3, 5) for the
//! transaction channel (Tasks 1-7). Lives as an integration test because the
//! whole surface it exercises (`Session`, `Tx`, `control::op::*`) is already
//! `pub` through `aura_lib::control` — no visibility changes were needed to
//! reach it from here, which is why this suite sits in `tests/` rather than
//! as a `#[cfg(test)]` module inside `src/control/session.rs` (that would
//! have required nothing extra either, but this keeps property-test-only
//! dependencies, like `proptest`, out of the crate's own `#[cfg(test)]`
//! compilation unit and mirrors how the crate already separates unit tests
//! (in-module) from integration coverage (this directory)).
//!
//! Test helpers here (`fresh_session_3_tracks`, `test_track`, `user_meta`,
//! `set_gain`) are deliberately NOT the private ones in
//! `src/control/session.rs`'s `#[cfg(test)]` module (those are crate-private
//! and unreachable from an integration test) — this file defines its own,
//! parallel but independent.
//!
//! Gate B (Task 8) lifts Task 1's original clip-free exclusion:
//! `arb_op_batches`'s `TrackAdd`/`TrackRemove` now attach 0..2 freshly-minted
//! clips, so `undo_round_trip`'s byte-stability oracle also covers
//! clip-carrying histories, not just bare track rows. (The dedicated
//! delete-then-undo identity property — random SUBSETS of tracks removed one
//! at a time, with interleaved clip ownership across the whole store — lives
//! in `tests/identity_properties.rs`; this file's coverage is the general
//! Gate A op-batch fuzzer, now clip-aware.)

use std::collections::HashMap;

use proptest::prelude::*;

use aura_lib::audio::types::{Clip, Store, TrackState};
use aura_lib::control::op::{Actor, ObjectRef, Op, PropPath, TxMeta};
use aura_lib::control::Session;
use aura_lib::ids::{ContentId, LaneId, NoteId, SourceId};
use aura_lib::midi::{MeterEvent, MidiClip, MidiNote, MidiStore, TempoEvent};

// ---------------------------------------------------------------------------
// Local test helpers (independent of session.rs's private #[cfg(test)] ones)
// ---------------------------------------------------------------------------

/// A session seeded with exactly 3 tracks, ids `t-1`..`t-3`, no clips. The
/// property strategy's model (`alive: Vec<String>`) starts from these same
/// three ids — keep them in sync if either side changes.
fn fresh_session_3_tracks() -> parking_lot::Mutex<Session> {
    let mut store = Store::default();
    for id in SEED_IDS {
        store.tracks.push(test_track(id));
    }
    parking_lot::Mutex::new(Session::new(store, MidiStore::default()))
}

const SEED_IDS: [&str; 3] = ["t-1", "t-2", "t-3"];

/// A standalone `TrackState` row with values inside every clamp range
/// (`session.rs::write_prop`), used both for the seeded session and for
/// `TrackAdd`/`TrackRemove` op payloads generated by the strategy.
fn test_track(id: &str) -> TrackState {
    TrackState {
        id: id.into(),
        name: format!("Track {id}"),
        kind: "audio".into(),
        gain_db: 0.0,
        pan: 0.0,
        muted: false,
        soloed: false,
        armed: false,
        color: "#7c9cff".into(),
        instrument_id: None,
        inserts: Vec::new(),
    }
}

fn user_meta(label: &str) -> TxMeta {
    TxMeta { actor: Actor::User, run: "prop-run".into(), label: label.into(), transient: false }
}

/// A standalone `Clip` row for `TrackAdd`/`TrackRemove` op payloads (Gate B
/// clip-carrying coverage). The empty/default `SourceId` is the documented
/// "unassigned" sentinel (`audio/types.rs::Clip::source_id`) — fine here,
/// these clips never reach the engine's decode cache.
fn test_clip(id: &str, track_id: &str) -> Clip {
    Clip {
        id: id.into(),
        track_id: track_id.into(),
        name: format!("Clip {id}"),
        source_path: "audio/x.wav".into(),
        source_id: SourceId::default(),
        source_channels: 2,
        source_sample_rate: 48_000,
        source_length_samples: 48_000,
        timeline_start_samples: 0,
        offset_samples: 0,
        length_samples: 48_000,
        gain_db: 0.0,
        fade_in_samples: 0,
        fade_out_samples: 0,
        content_id: ContentId::mint(),
        lane_id: LaneId::default_for_track(track_id),
    }
}

/// A standalone `MidiClip` row for `MidiClipAdd`/`MidiClipRemove` op
/// payloads (Plan E Task 5), mirroring `test_clip`'s role for audio clips.
fn test_midi_clip(id: &str, track_id: &str) -> MidiClip {
    MidiClip {
        id: id.into(),
        track_id: track_id.into(),
        name: format!("MIDI {id}"),
        timeline_start_ticks: 0,
        length_ticks: 3840,
        notes: vec![],
        next_note_id: 1,
        content_id: ContentId::mint(),
        lane_id: LaneId::default_for_track(track_id),
        content_length_ticks: None,
        transpose_semitones: 0,
        velocity_offset: 0,
    }
}

/// `from` is intentionally `Null`: it's advisory only — `apply_raw` re-reads
/// truth from the store and ignores the caller's `from`.
fn set_gain(track_id: &str, to: f64) -> Op {
    Op::Set {
        object: ObjectRef::Track(track_id.into()),
        path: PropPath::Gain,
        from: serde_json::Value::Null,
        to: serde_json::json!(to),
    }
}

/// Deep, byte-identical snapshot of session STATE — `Store` + `MidiStore`'s
/// public fields, serialized to canonical JSON. Deliberately does NOT reach
/// `Session.rev` (it's `pub(crate)`, unreachable from this integration test
/// crate anyway) — `rev` increments on every transaction including undo
/// transactions, which is correct behavior, not something snapshot equality
/// should be sensitive to. Round-2 §2.4: `Store` no longer owns a `slots`
/// map (slots are per-graph-generation state derived fresh by the engine on
/// every rebuild, never part of the document) — so there is nothing RT-side
/// left to snapshot here; `tracks`/`clips` order IS the display order the
/// slots would be derived from, and that's already covered below.
fn snapshot(m: &parking_lot::Mutex<Session>) -> String {
    #[derive(serde::Serialize)]
    struct StoreSnap<'a> {
        transport: &'a aura_lib::audio::types::TransportState,
        tracks: &'a Vec<TrackState>,
        clips: &'a Vec<aura_lib::audio::types::Clip>,
        project_dir: &'a Option<std::path::PathBuf>,
        project_name: &'a Option<String>,
        created_at: &'a Option<String>,
    }
    #[derive(serde::Serialize)]
    struct MidiSnap<'a> {
        ppq: u32,
        tempo_events: &'a Vec<aura_lib::midi::TempoEvent>,
        // Plan E Task 5: TempoSet mutates the meter map too — must be part
        // of the snapshot or a meter round-trip bug would slip past Gate 1.
        meter_events: &'a Vec<aura_lib::midi::MeterEvent>,
        clips: &'a Vec<aura_lib::midi::MidiClip>,
        loaded_dir: &'a Option<std::path::PathBuf>,
    }
    #[derive(serde::Serialize)]
    struct Snap<'a> {
        store: StoreSnap<'a>,
        midi: MidiSnap<'a>,
    }

    let g = m.lock();
    let snap = Snap {
        store: StoreSnap {
            transport: &g.store.transport,
            tracks: &g.store.tracks,
            clips: &g.store.clips,
            project_dir: &g.store.project_dir,
            project_name: &g.store.project_name,
            created_at: &g.store.created_at,
        },
        midi: MidiSnap {
            ppq: g.midi.ppq,
            tempo_events: &g.midi.tempo_events,
            meter_events: &g.midi.meter_events,
            clips: &g.midi.clips,
            loaded_dir: &g.midi.loaded_dir,
        },
    };
    serde_json::to_string(&snap).expect("snapshot fields are all plain-data Serialize")
}

/// Map of `midi clip id -> next_note_id`, read off store truth (Plan E Task
/// 5 / scope ruling 3's "assert monotonicity separately" half).
fn watermarks(m: &parking_lot::Mutex<Session>) -> HashMap<String, u32> {
    m.lock().midi.clips.iter().map(|c| (c.id.to_string(), c.next_note_id)).collect()
}

/// THE ORACLE CHANGE (binding scope ruling 3): re-parse a `snapshot()`
/// string and zero every midi clip's `nextNoteId` field before the
/// byte-identical comparison. Rationale: `MidiSetNotes`'s inverse NEVER
/// rewinds the watermark (ADR 0001 — ids are never reused, so an undo
/// cannot "give back" an id it already handed out), so `next_note_id` is
/// the one field a round trip (undo, OR a same-transaction rollback that
/// replays inverses immediately) is NOT expected to restore — unlike every
/// other field, which IS. Masking it here (rather than excluding clips from
/// the snapshot entirely) keeps every OTHER clip field — notes (incl. their
/// individual `noteId`s, which the "keep-rule-safe" property strategy below
/// guarantees ARE restored byte-identically), bounds, name, ids — under the
/// same strict byte-identical scrutiny it always had. The asymmetry this
/// masks is checked separately, not silently ignored — see `watermarks`
/// and its call site in `undo_round_trip`.
fn mask_watermarks(snapshot_json: &str) -> String {
    let mut v: serde_json::Value =
        serde_json::from_str(snapshot_json).expect("snapshot() always emits valid JSON");
    if let Some(clips) = v.pointer_mut("/midi/clips").and_then(|c| c.as_array_mut()) {
        for clip in clips {
            if let Some(obj) = clip.as_object_mut() {
                obj.insert("nextNoteId".to_string(), serde_json::json!(0));
            }
        }
    }
    serde_json::to_string(&v).expect("re-serializing a parsed Value never fails")
}

// ---------------------------------------------------------------------------
// arb_op_batches: a Vec<Vec<Op>> strategy, model-threaded so every generated
// op targets a currently-alive track id (Sets and Removes) or introduces a
// genuinely fresh one (Adds) — batches are valid by construction. Threading
// happens in a deterministic `prop_map` over pure random primitives (usize
// picks + typed values), not by calling anything nondeterministic (e.g. no
// `Uuid::new_v4()` inside the map) — that keeps proptest's shrinker honest:
// shrinking the underlying raw ints/bools must still resolve to the same
// concrete ops on replay.
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
enum SetKind {
    Gain(f64),
    Pan(f64),
    Muted(bool),
    Soloed(bool),
    Armed(bool),
}

#[derive(Debug, Clone)]
enum MidiBoundsKind {
    TimelineStartTicks(u64),
    /// Includes 0 so the strategy exercises `write_midi_prop`'s clamp.
    LengthTicks(u64),
    ContentLengthTicks(Option<u64>),
}

#[derive(Debug, Clone)]
enum RawAction {
    /// `pick` selects an alive track by `pick % alive.len()`.
    Set(usize, SetKind),
    /// `n_clips` (0..=2) freshly-minted clips travel with the new row
    /// (Gate B: Task 1's clip-free exclusion lifted).
    Add(usize),
    /// `pick` selects an alive track by `pick % alive.len()`; `n_clips`
    /// (0..=2) freshly-minted clips are attached to the op payload — advisory
    /// only (`apply_raw` collects the REAL removed clips from store truth),
    /// but exercised anyway so a clip-carrying `TrackRemove` payload is part
    /// of the fuzzed op vocabulary too.
    Remove(usize, usize),
    /// Plan E Task 3: `pick` selects an alive CLIP by `pick % alive_clips.len()`;
    /// `to` is the new `timelineStartSamples`.
    ClipMove(usize, u64),
    /// Plan E Task 3: mint a fresh clip on an alive TRACK, `track_pick`
    /// selects it by `track_pick % alive.len()`.
    ClipAdd(usize),
    /// Plan E Task 3: `pick` selects an alive CLIP by
    /// `pick % alive_clips.len()` to remove.
    ClipRemove(usize),
    /// Plan E Task 5: mint a fresh MIDI clip on an alive TRACK, `track_pick`
    /// selects it by `track_pick % alive.len()`.
    MidiClipAdd(usize),
    /// Plan E Task 5: `pick` selects an alive MIDI clip by
    /// `pick % alive_midi_clips.len()` to remove.
    MidiClipRemove(usize),
    /// Plan E Task 5: `pick` selects an alive MIDI clip; `kind` is the new
    /// bounds value.
    MidiBoundsSet(usize, MidiBoundsKind),
    /// Plan E Task 5: `pick` selects an alive MIDI clip; `n_new` (0..=2)
    /// brand-new notes are APPENDED to whatever notes the clip already has
    /// — deliberately never removed. This keeps every generated payload
    /// "keep-rule-safe": it always re-sends every currently-live note id
    /// unchanged, so `assign_incoming_note_ids`'s keep-rule (midi/mod.rs)
    /// always recognizes them and `undo_round_trip`'s byte-identical oracle
    /// holds on full note CONTENT, including individual `noteId`s — not
    /// just the watermark (scope ruling 3 masks ONLY `next_note_id`, which
    /// implies note ids themselves ARE expected to round-trip exactly).
    /// Deleting notes here would sometimes force a mint-fresh-identity
    /// round trip that is byte-identical in content but not in `noteId` (by
    /// design — ADR 0001: a dropped id is never resurrected) — that path is
    /// exercised directly by the dedicated `session.rs` unit tests instead
    /// of here.
    MidiSetNotes(usize, usize),
    /// Plan E Task 5: replace the tempo/meter map wholesale. Not
    /// model-threaded against `alive`/`alive_clips` — `TempoSet` doesn't
    /// touch tracks or clips, only `midi.{ppq,tempo_events,meter_events}` +
    /// the `transport.tempo_bpm` mirror.
    TempoSet(f64),
}

fn set_kind_strategy() -> impl Strategy<Value = SetKind> {
    prop_oneof![
        (-160.0f64..=24.0f64).prop_map(SetKind::Gain),
        (-1.0f64..=1.0f64).prop_map(SetKind::Pan),
        any::<bool>().prop_map(SetKind::Muted),
        any::<bool>().prop_map(SetKind::Soloed),
        any::<bool>().prop_map(SetKind::Armed),
    ]
}

fn midi_bounds_kind_strategy() -> impl Strategy<Value = MidiBoundsKind> {
    prop_oneof![
        (0u64..=20_000).prop_map(MidiBoundsKind::TimelineStartTicks),
        (0u64..=5_000).prop_map(MidiBoundsKind::LengthTicks),
        proptest::option::of(1u64..=5_000).prop_map(MidiBoundsKind::ContentLengthTicks),
    ]
}

/// Weighted so removes land often enough (against a growing/shrinking model,
/// starting from 3 seeded tracks) to exercise restore-at-varied-index, while
/// Adds keep replenishing the pool so batches don't degenerate into
/// all-no-op Sets/Removes against an empty track list. Plan E Task 3 adds
/// ClipMove/ClipAdd/ClipRemove at weights 2/1/1 alongside the existing
/// 4 Set / 2 Add / 3 Remove track actions. Plan E Task 5 adds the MIDI half
/// the same way: MidiClipAdd/Remove at 1/1 (structural, mirrors ClipAdd/
/// Remove's weight), MidiBoundsSet at 2 (mirrors ClipMove), MidiSetNotes at
/// 1, TempoSet at 1 (store-wide, not model-threaded).
fn raw_action_strategy() -> impl Strategy<Value = RawAction> {
    prop_oneof![
        4 => (any::<usize>(), set_kind_strategy()).prop_map(|(p, k)| RawAction::Set(p, k)),
        2 => (0usize..=2).prop_map(RawAction::Add),
        3 => (any::<usize>(), 0usize..=2).prop_map(|(p, n)| RawAction::Remove(p, n)),
        2 => (any::<usize>(), 0u64..=10_000_000u64).prop_map(|(p, to)| RawAction::ClipMove(p, to)),
        1 => any::<usize>().prop_map(RawAction::ClipAdd),
        1 => any::<usize>().prop_map(RawAction::ClipRemove),
        1 => any::<usize>().prop_map(RawAction::MidiClipAdd),
        1 => any::<usize>().prop_map(RawAction::MidiClipRemove),
        2 => (any::<usize>(), midi_bounds_kind_strategy()).prop_map(|(p, k)| RawAction::MidiBoundsSet(p, k)),
        1 => (any::<usize>(), 0usize..=2).prop_map(|(p, n)| RawAction::MidiSetNotes(p, n)),
        1 => (40.0f64..=300.0f64).prop_map(RawAction::TempoSet),
    ]
}

/// Mint `n` freshly-numbered clips owned by `track_id`, advancing
/// `clip_counter` (kept separate from the track-id `counter` so ids never
/// collide across the two families).
fn mint_clips(track_id: &str, n: usize, clip_counter: &mut u32) -> Vec<Clip> {
    (0..n)
        .map(|_| {
            let cid = format!("clip-{}", *clip_counter);
            *clip_counter += 1;
            test_clip(&cid, track_id)
        })
        .collect()
}

/// Plan E Task 5's threaded model for an alive MIDI clip: `note_ids` and
/// `next_note_id` are kept in exact lockstep with real store truth (never
/// approximated) because `MidiSetNotes`'s "keep-rule-safe" generation
/// (`RawAction::MidiSetNotes`'s doc comment) depends on knowing the EXACT
/// live ids to re-send, and the exact next id(s) `assign_incoming_note_ids`
/// will mint for brand-new notes appended after them (see `resolve_one`'s
/// `MidiSetNotes` arm for how that determinism is arranged: kept notes
/// always sort before new notes by `tick`, so mint order == append order).
#[derive(Debug, Clone)]
struct MidiClipModel {
    id: String,
    note_ids: Vec<u32>,
    next_note_id: u32,
}

/// Resolves one `RawAction` against the threaded model, mutating `alive`
/// (track ids), `alive_clips` (`(clip_id, track_id)` pairs — Plan E Task 3,
/// threaded the same way `alive` is), `alive_midi_clips` (Plan E Task 5,
/// same idea for MIDI clips), `counter` (fresh, distinct generated-track
/// ids), `clip_counter` (fresh, distinct generated-clip ids) and
/// `midi_clip_counter` (fresh, distinct generated-midi-clip ids). Returns
/// `None` when the action is a no-op given current model state (e.g. a
/// Set/Remove drawn while `alive`/`alive_clips`/`alive_midi_clips` is empty)
/// — the caller filters those out, so a batch may end up shorter than
/// requested (never invalid).
fn resolve_one(
    action: RawAction, alive: &mut Vec<String>, alive_clips: &mut Vec<(String, String)>,
    alive_midi_clips: &mut Vec<MidiClipModel>,
    counter: &mut u32, clip_counter: &mut u32, midi_clip_counter: &mut u32,
) -> Option<Op> {
    match action {
        RawAction::Set(pick, kind) => {
            if alive.is_empty() {
                return None;
            }
            let id = alive[pick % alive.len()].clone();
            let (path, to) = match kind {
                SetKind::Gain(v) => (PropPath::Gain, serde_json::json!(v)),
                SetKind::Pan(v) => (PropPath::Pan, serde_json::json!(v)),
                SetKind::Muted(v) => (PropPath::Muted, serde_json::json!(v)),
                SetKind::Soloed(v) => (PropPath::Soloed, serde_json::json!(v)),
                SetKind::Armed(v) => (PropPath::Armed, serde_json::json!(v)),
            };
            Some(Op::Set { object: ObjectRef::Track(id.into()), path, from: serde_json::Value::Null, to })
        }
        RawAction::Add(n_clips) => {
            let id = format!("gen-{}", *counter);
            *counter += 1;
            alive.push(id.clone());
            // `clip_indices` stays empty: `apply_raw`'s TrackAdd arm falls
            // back to appending (`clip_indices.len() == clips.len()` is
            // false for empty indices against non-empty clips), which is
            // exactly right for a genuinely NEW row — there is no prior
            // position to restore.
            let clips = mint_clips(&id, n_clips, clip_counter);
            for c in &clips {
                alive_clips.push((c.id.to_string(), id.clone()));
            }
            Some(Op::TrackAdd {
                track: test_track(&id), index: alive.len() - 1, clips, clip_indices: vec![],
                automation_clips: vec![], bindings: vec![],
            })
        }
        RawAction::Remove(pick, n_clips) => {
            if alive.is_empty() {
                return None;
            }
            let idx = pick % alive.len();
            let id = alive.remove(idx);
            // Store truth: the removed track's clips leave WITH it
            // (`apply_raw`'s `Op::TrackRemove` arm), so the model drops
            // them from `alive_clips` too — mirrors `alive.remove` above.
            alive_clips.retain(|(_, track_id)| track_id != &id);
            // `track`/`clips`/`clip_indices` are all advisory-ignored by
            // `apply_raw` (store truth wins for the removed row and its
            // real clips) — only `.id` matters for finding the row to
            // remove. Attaching minted clips here anyway exercises that
            // "advisory, ignored" path even when the payload itself carries
            // clips.
            let clips = mint_clips(&id, n_clips, clip_counter);
            Some(Op::TrackRemove { track: test_track(&id), index: idx, clips, clip_indices: vec![] })
        }
        RawAction::ClipMove(pick, to) => {
            if alive_clips.is_empty() {
                return None;
            }
            let (clip_id, _track_id) = alive_clips[pick % alive_clips.len()].clone();
            Some(Op::Set {
                object: ObjectRef::Clip(clip_id.into()),
                path: PropPath::TimelineStartSamples,
                from: serde_json::Value::Null,
                to: serde_json::json!(to),
            })
        }
        RawAction::ClipAdd(track_pick) => {
            if alive.is_empty() {
                return None;
            }
            let track_id = alive[track_pick % alive.len()].clone();
            let cid = format!("gen-clip-{}", *clip_counter);
            *clip_counter += 1;
            let clip = test_clip(&cid, &track_id);
            let index = alive_clips.len();
            alive_clips.push((cid, track_id));
            Some(Op::ClipAdd { clip, index })
        }
        RawAction::ClipRemove(pick) => {
            if alive_clips.is_empty() {
                return None;
            }
            let idx = pick % alive_clips.len();
            let (clip_id, track_id) = alive_clips.remove(idx);
            // `clip`/`index` beyond `.id` are advisory-ignored by
            // `apply_raw` (store truth wins), same precedent as
            // `TrackRemove` above.
            Some(Op::ClipRemove { clip: test_clip(&clip_id, &track_id), index: idx })
        }
        RawAction::MidiClipAdd(track_pick) => {
            if alive.is_empty() {
                return None;
            }
            let track_id = alive[track_pick % alive.len()].clone();
            let cid = format!("gen-midi-{}", *midi_clip_counter);
            *midi_clip_counter += 1;
            let clip = test_midi_clip(&cid, &track_id);
            let index = alive_midi_clips.len();
            alive_midi_clips.push(MidiClipModel { id: cid, note_ids: vec![], next_note_id: 1 });
            Some(Op::MidiClipAdd { clip, index })
        }
        RawAction::MidiClipRemove(pick) => {
            if alive_midi_clips.is_empty() {
                return None;
            }
            let idx = pick % alive_midi_clips.len();
            let model = alive_midi_clips.remove(idx);
            // `clip`/`index` beyond `.id` are advisory-ignored by
            // `apply_raw` (store truth wins), same precedent as
            // `ClipRemove` above — `track_id` here is never read.
            Some(Op::MidiClipRemove { clip: test_midi_clip(&model.id, "unused"), index: idx })
        }
        RawAction::MidiBoundsSet(pick, kind) => {
            if alive_midi_clips.is_empty() {
                return None;
            }
            let id = alive_midi_clips[pick % alive_midi_clips.len()].id.clone();
            let (path, to) = match kind {
                MidiBoundsKind::TimelineStartTicks(v) => (PropPath::TimelineStartTicks, serde_json::json!(v)),
                MidiBoundsKind::LengthTicks(v) => (PropPath::LengthTicks, serde_json::json!(v)),
                MidiBoundsKind::ContentLengthTicks(v) => (
                    PropPath::ContentLengthTicks,
                    match v {
                        Some(v) => serde_json::json!(v),
                        None => serde_json::Value::Null,
                    },
                ),
            };
            Some(Op::Set { object: ObjectRef::MidiClip(id.into()), path, from: serde_json::Value::Null, to })
        }
        RawAction::MidiSetNotes(pick, n_new) => {
            if alive_midi_clips.is_empty() {
                return None;
            }
            let idx = pick % alive_midi_clips.len();
            let model = &mut alive_midi_clips[idx];
            // Kept notes: re-send EVERY currently-live id unchanged (content
            // varies only in `tick`, kept low) — "keep-rule-safe" by
            // construction (see `RawAction::MidiSetNotes`'s doc comment).
            let mut notes: Vec<MidiNote> = model
                .note_ids
                .iter()
                .enumerate()
                .map(|(i, &id)| MidiNote {
                    tick: (i as u32) * 40,
                    length_ticks: 480,
                    key: 60,
                    velocity: 100,
                    channel: 0,
                    note_id: NoteId(id),
                })
                .collect();
            // New notes: id 0 (mint), `tick` deliberately far past any kept
            // note's tick so `assign_incoming_note_ids`'s sort-by-(tick,key)
            // places them AFTER every kept note — the mint order then
            // exactly matches `j`'s order, so the model can predict the
            // exact ids that will be minted without observing the result.
            for j in 0..n_new {
                notes.push(MidiNote {
                    tick: 100_000 + (j as u32) * 40,
                    length_ticks: 480,
                    key: 61,
                    velocity: 100,
                    channel: 0,
                    note_id: NoteId(0),
                });
            }
            let n_new = n_new as u32;
            let new_ids: Vec<u32> = (model.next_note_id..model.next_note_id + n_new).collect();
            model.note_ids.extend(new_ids);
            model.next_note_id += n_new;
            Some(Op::MidiSetNotes { clip: model.id.clone().into(), notes })
        }
        RawAction::TempoSet(bpm) => Some(Op::TempoSet {
            ppq: 960,
            events: vec![TempoEvent { tick: 0, bpm }],
            meter: vec![MeterEvent { tick: 0, num: 4, den: 4 }],
        }),
    }
}

fn arb_op_batches(num_batches: std::ops::Range<usize>) -> impl Strategy<Value = Vec<Vec<Op>>> {
    proptest::collection::vec(proptest::collection::vec(raw_action_strategy(), 1..=4), num_batches)
        .prop_map(|raw_batches| {
            let mut alive: Vec<String> = SEED_IDS.iter().map(|s| s.to_string()).collect();
            let mut alive_clips: Vec<(String, String)> = Vec::new();
            let mut alive_midi_clips: Vec<MidiClipModel> = Vec::new();
            let mut counter: u32 = 0;
            let mut clip_counter: u32 = 0;
            let mut midi_clip_counter: u32 = 0;
            raw_batches
                .into_iter()
                .map(|batch| {
                    batch
                        .into_iter()
                        .filter_map(|a| {
                            resolve_one(
                                a, &mut alive, &mut alive_clips, &mut alive_midi_clips,
                                &mut counter, &mut clip_counter, &mut midi_clip_counter,
                            )
                        })
                        .collect::<Vec<Op>>()
                })
                .collect()
        })
}

// ---------------------------------------------------------------------------
// Gate tests
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// Gate test 1: apply all, undo all, byte-identical state.
    #[test]
    fn undo_round_trip(batches in arb_op_batches(1..20)) {
        let m = fresh_session_3_tracks();
        let before = snapshot(&m);
        let mut undo_stack = vec![];
        for b in batches {
            if let Ok(c) = Session::transact(&m, user_meta("p"), |tx| {
                for op in b {
                    tx.apply(op)?;
                }
                Ok(())
            }) {
                undo_stack.push(c.inverses);
            } // Err = rolled back = state unchanged; nothing pushed.
        }
        // Scope ruling 3's monotonicity half: capture the peak (post-apply,
        // pre-undo) watermark per alive midi clip. Any clip still alive
        // AFTER the full undo below (uncommon — most midi clips added
        // during the run get removed again by their own `MidiClipAdd`'s
        // inverse, so this is frequently a vacuous check, but it's a real
        // guard against a future regression that rewinds a survivor's
        // watermark) must never show a SMALLER `next_note_id` than its peak.
        let wm_peak = watermarks(&m);
        for inv in undo_stack.into_iter().rev() {
            Session::transact(&m, user_meta("undo"), |tx| {
                for op in inv {
                    tx.apply(op)?;
                }
                Ok(())
            })
            .unwrap();
        }
        let after = snapshot(&m);
        // THE ORACLE CHANGE (binding scope ruling 3) — see `mask_watermarks`'
        // doc for the full rationale: `next_note_id` is expected to differ
        // (only ever upward) after a round trip; every other field is not.
        prop_assert_eq!(mask_watermarks(&after), mask_watermarks(&before));
        let wm_final = watermarks(&m);
        for (id, peak) in &wm_peak {
            if let Some(final_wm) = wm_final.get(id) {
                prop_assert!(
                    final_wm >= peak,
                    "clip {id}: watermark rewound {peak} -> {final_wm} across undo"
                );
            }
        }
    }

    /// Gate test 3: a failing batch leaves the session exactly as it was.
    #[test]
    fn atomicity(prefix in arb_op_batches(1..5)) {
        let m = fresh_session_3_tracks();
        let before = snapshot(&m);
        let _ = Session::transact(&m, user_meta("f"), |tx| {
            for b in prefix {
                for op in b {
                    tx.apply(op)?;
                }
            }
            tx.apply(set_gain("no-such-track", 0.5)) // guaranteed failure
        });
        // Same masking as `undo_round_trip`: this transaction's OWN
        // rollback replays inverses immediately (Session::transact's Err
        // path), which hits the identical watermark asymmetry — a
        // `MidiSetNotes` that minted new ids before the guaranteed failure
        // has its notes fully restored by the rollback, but not its
        // `next_note_id` (ADR 0001, never rewound).
        prop_assert_eq!(mask_watermarks(&snapshot(&m)), mask_watermarks(&before));
    }
}

/// Gate test 5: every committed batch carries resolvable attribution.
#[test]
fn attribution_survives_commit() {
    let m = fresh_session_3_tracks();
    let c = Session::transact(
        &m,
        TxMeta { actor: Actor::Agent { tool: "set_track_mix".into() }, run: "run-42".into(), label: "agent mix".into(), transient: false },
        |tx| tx.apply(set_gain("t-1", 0.5)),
    )
    .unwrap();
    assert!(matches!(c.meta.actor, Actor::Agent { ref tool } if tool == "set_track_mix"));
    assert_eq!(c.meta.run, "run-42");

    // Plan E Task 13 (§7 test 5's "Actor::Engine appears where expected"):
    // the engine control thread's own commits (recording finalize,
    // auto-stop, ...) carry `Actor::Engine`, resolvable through the exact
    // same `Session::transact` path as every other actor — attribution
    // isn't special-cased per actor kind.
    let c2 = Session::transact(&m, TxMeta::engine("stop recording"), |tx| tx.apply(set_gain("t-2", 0.25)))
        .unwrap();
    assert!(matches!(c2.meta.actor, Actor::Engine), "engine-originated commits carry Actor::Engine");
    assert!(!c2.meta.transient, "TxMeta::engine() defaults to non-transient (finalize is a real edit)");
}
